admin_toolbar.settings:
  type: config_object
  label: 'Admin Toolbar settings'
  mapping:
    menu_depth:
      type: integer
      label: 'Depth of displayed menu'
    disable_sticky:
      type: boolean
      label: 'Disable sticky toolbar'
